spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/association
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 9090

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
